---
all:
  children:
    lxc:
      hosts:
        mongodb:
          ansible_host: 192.168.1.53
          proxmox_vmid: 1235
          ansible_connection: community.proxmox.proxmox_pct_remote
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/proxmox_dev_ansible_private_key
          ansible_proxmox_pct_vm_id: 1235
        vault:
          ansible_host: 192.168.1.53
          proxmox_vmid: 1236
          ansible_connection: community.proxmox.proxmox_pct_remote
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/proxmox_dev_ansible_private_key
          ansible_proxmox_pct_vm_id: 1236
        jumpbox:
          ansible_host: 192.168.1.53
          proxmox_vmid: 1238
          ansible_connection: community.proxmox.proxmox_pct_remote
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/proxmox_dev_ansible_private_key
          ansible_proxmox_pct_vm_id: 1238
        authentik:
          ansible_host: 192.168.1.53
          proxmox_vmid: 1239
          ansible_connection: community.proxmox.proxmox_pct_remote
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/proxmox_dev_ansible_private_key
          ansible_proxmox_pct_vm_id: 1239
        grafana:
          ansible_host: 192.168.1.53
          proxmox_vmid: 1240
          ansible_connection: community.proxmox.proxmox_pct_remote
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/proxmox_dev_ansible_private_key
          ansible_proxmox_pct_vm_id: 1240
        unbound:
          ansible_host: 192.168.1.53
          proxmox_vmid: 1241
          ansible_connection: community.proxmox.proxmox_pct_remote
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/proxmox_dev_ansible_private_key
          ansible_proxmox_pct_vm_id: 1241
        nginx:
          ansible_host: 192.168.1.53
          proxmox_vmid: 1242
          ansible_connection: community.proxmox.proxmox_pct_remote
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/proxmox_dev_ansible_private_key
          ansible_proxmox_pct_vm_id: 1242
        prometheus:
          ansible_host: 192.168.1.53
          proxmox_vmid: 1243
          ansible_connection: community.proxmox.proxmox_pct_remote
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/proxmox_dev_ansible_private_key
          ansible_proxmox_pct_vm_id: 1243
        gitlab_runner:
          ansible_host: 192.168.1.53
          proxmox_vmid: 1244
          ansible_connection: community.proxmox.proxmox_pct_remote
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/proxmox_dev_ansible_private_key
          ansible_proxmox_pct_vm_id: 1244
    proxmox:
      hosts:
        proxmox-1:
          ansible_host: 192.168.1.53
          ansible_user: root
          ansible_private_key_file: ~/.ssh/id_ed25519
          ansible_ssh_common_args: '-o SetEnv=GPG_TTY=$(tty)'
      vars:
        env: "dev"
