all:
  children:
    lxc:
      hosts:
        mongodb:
          ansible_host: 192.168.1.53
          proxmox_vmid: 1235
          ansible_connection: community.proxmox.proxmox_pct_remote
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/proxmox_dev_ansible_private_key
          ansible_proxmox_pct_vm_id: 1235
        vault:
          ansible_host: 192.168.1.53
          proxmox_vmid: 1236
          ansible_connection: community.proxmox.proxmox_pct_remote
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/proxmox_dev_ansible_private_key
          ansible_proxmox_pct_vm_id: 1236
    proxmox:
      hosts:
        proxmox-1:
          ansible_host: 192.168.1.53
          ansible_user: root
          ansible_private_key_file: ~/.ssh/id_ed25519
          ansible_ssh_common_args: '-o SetEnv=GPG_TTY=$(tty)'
      vars:
        env: "dev"
