---
- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true

- name: Reload node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: reloaded

- name: Restart nginx_exporter
  ansible.builtin.systemd:
    name: nginx_exporter
    state: restarted
    daemon_reload: true

- name: Reload nginx_exporter
  ansible.builtin.systemd:
    name: nginx_exporter
    state: reloaded
