---
- name: restart_node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
    daemon_reload: true

- name: reload_node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: reloaded

- name: restart_nginx_exporter
  ansible.builtin.systemd:
    name: nginx_exporter
    state: restarted
    daemon_reload: true

- name: reload_nginx_exporter
  ansible.builtin.systemd:
    name: nginx_exporter
    state: reloaded
