---
- name: Set user shell to zsh
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: /bin/zsh

- name: Download ohmyzsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "{{ user_home }}/install.sh"
    mode: '0755'
  become: true
  become_user: "{{ item.name }}"

- name: Check if .oh-my-zsh directory exists
  ansible.builtin.stat:
    path: "{{ user_home }}/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Run Oh My Zsh installation script
  ansible.builtin.command: sh "{{ user_home }}/install.sh" --unattended
  register: ohmyzsh_result
  failed_when: "'FAILED' in ohmyzsh_result.stderr"
  changed_when: not oh_my_zsh_stat.stat.exists
  when: not oh_my_zsh_stat.stat.exists
  become: true
  become_user: "{{ item.name }}"

- name: Install PowerLevel10K
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ user_home }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
  become: true
  become_user: "{{ item.name }}"

- name: Install autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ user_home }}/.oh-my-zsh/custom//plugins/zsh-autosuggestions"
  become: true
  become_user: "{{ item.name }}"

- name: Install syntax hilight
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ user_home }}/.oh-my-zsh/custom//plugins/zsh-syntax-highlighting"
  become: true
  become_user: "{{ item.name }}"

- name: Copy .zshrc config
  ansible.builtin.copy:
    src: files/zshrc
    dest: "{{ user_home }}/.zshrc"
    mode: "0644"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"

- name: Copy .p10k.zsh config
  ansible.builtin.copy:
    src: files/p10k.zsh
    dest: "{{ user_home }}/.p10k.zsh"
    mode: "0644"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
